### ISSUE TITLE
Add common debugging output for CI jobs in testing workflows

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-common#134]
This can be a uds tasks that potentially takes an input of "types" of info to dump at the end of a job running and then gets added to the [test](https://github.com/defenseunicorns/uds-common/blob/859a9b2469c8a6c24c414fe34b127ec5677aea62/.github/actions/test/action.yaml#L25) action, optionally by an input. 

Or a dedicated action called from the workflow that has an input to drive the debug dump info.  See the [debug action](https://github.com/defenseunicorns/uds-core/blob/main/.github/actions/debug-output/action.yaml) in uds-core for reference

**Comment by zachariahmiller** [comment]
CC @mjnagel we had discussed

**Comment by Racer159** [comment]
Partly implemented with https://github.com/defenseunicorns/uds-common/pull/135
