### ISSUE TITLE
Create reusable "docker login" task that supports periodic retry on failure

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-common#27]
Context for this is registry1 logins are very intermittent with success. Criteria we would like:
- UDS task (not a github action)
- Inputs for registry, username, password
- `maxRetries` set to something, maybe an input or maybe just 10
- delays in between retries, i.e. add a sleep if this is a retry

**Comment by mjnagel** [comment]
After some @MxNxPx investigation this might be unnecessary... `uds zarf tools registry login` will always succeed, adding the auth to the users docker-config without validating. This might work in our favor, and then zarf pulls have built in retries in cases of auth failure there... testing with https://github.com/defenseunicorns/uds-core/pull/154/commits/bf762eeb907791da6b22ddb7afb234c3c050479a

**Comment by TristanHoladay** [comment]
Is this accomplished now that @MxNxPx registry login task is part of this repo and used in uds-core?
